# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-26 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0037_auto_20210414_0026'),
        ('forum', '0003_transcript_pending_advisors'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='timetable',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.PersonalTimetable'),
        ),
    ]
