# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-19 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalexamshare',
            name='exam_year',
            field=models.CharField(default=None, max_length=4),
        ),
    ]
