# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-05-23 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0032_auto_20190512_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='questions',
            field=models.ManyToManyField(to='timetable.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(to='timetable.Answer'),
        ),
    ]
