# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-06-28 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0032_add_pilot_f19'),
    ]

    operations = [
        migrations.CreateModel(
            name='PILOTSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sections', models.ManyToManyField(to='timetable.Section')),
            ],
        ),
    ]
