# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-05-23 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0033_auto_20190523_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='timetable.Course'),
            preserve_default=False,
        ),
    ]
