# Generated by Django 2.2.18 on 2021-09-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0033_auto_20210724_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='favorite_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
